apiVersion: v1
kind: Service
metadata:
        name: scheduler-generator-app-svc
        labels:
                name: scheduler-generator-app-svc
                app: scheduler-generator-app
spec:
        type: NodePort
        selector:
                name: scheduler-generator-app-pod
                app: scheduler-generator-app
        ports:
                - port: 5000
