apiVersion: apps/v1
kind: Deployment
metadata:
        name: scheduler-generator-app-deploy
        labels:
                name: scheduler-generator-app-deploy
                app: scheduler-generator-app
spec:
        replicas: 1
        selector: 
                matchLabels:
                        name: scheduler-generator-app-pod
                        app: scheduler-generator-app
        template:
                metadata:
                        name: scheduler-generator-app-pod
                        labels:
                                name: scheduler-generator-app-pod
                                app: scheduler-generator-app
                spec:
                        containers:
                                - name: scheduler-generator-app
                                  image: itsssxuria/udemy_scheduler_generator
                                  ports:
                                          - containerPort: 5000

